site_name: Morenet documentation
site_url: http://http://iai-webserv.iai.kit.edu/morenet
site_description: Documentation for the morenet project
site_author: Tillmann Mühlpfordt
docs_dir: docs/

repo_name: advancedcontrol/code/morenet/morenet
repo_url: https://iai-vcs.iai.kit.edu/advancedcontrol/code/morenet/morenet
repo_name: 'GitLab'
   
theme:
    name: material
    navigation_depth: 2

extra_css:
    - 'css/extra.css'

markdown_extensions:
    - pymdownx.arithmatex
    - smarty
    - tables
    - toc
    - admonition
    - codehilite:
        linenums: True
    

plugins:
    - search
    - awesome-pages:
        collapse_single_pages: true

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

