title: rapidPF - Documentation
arrange:
    - index.md
    - introduction.md
    - installation.md
    - overview.md
    - example.md
    - assumptions.md
    - problem-formulation.md
    - mfiles
    